package br.com.devschool.movimento_caixa.visao;

import br.com.devschool.entidade.Funcionario;
import br.com.devschool.entidade.MovimentoCaixa;
import br.com.devschool.entidade.Terminal;
import br.com.devschool.funcionario.servico.FuncionarioServico;
import br.com.devschool.login.visao.LoginFrame;
import br.com.devschool.movimento_caixa.servico.MovimentoCaixaServico;
import br.com.devschool.terminal.servico.TerminalServico;
import br.com.devschool.util.FrameUtil;
import br.com.devschool.util.MensagemUtil;
import br.com.devschool.util.PDVException;
import br.com.devschool.util.StringUtil;
import br.com.devschool.util.enumerador.PerfilEnum;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

/**
 * @author ATILLA
 */
public class FechamentoCaixaFrame extends FrameUtil {

    private FuncionarioServico servico;
    private Funcionario funcionario = null;
    private Funcionario supervisor = null;
    private List<Terminal> terminais = new ArrayList();

    public FechamentoCaixaFrame() throws PDVException {
        try {
            servico = new FuncionarioServico();
        } catch (PDVException e) {
            addMensagemErro(e.getMessage());
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField();
        try{
            javax.swing.text.MaskFormatter data= new
            javax.swing.text.MaskFormatter("###.###.###-##");
            jFormattedTextFieldCpf = new 
            javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        jLabel3 = new javax.swing.JLabel();
        jComboBoxTerminal = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFundoFechamento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldCpfSupervisor = new javax.swing.JFormattedTextField();
        try{
            javax.swing.text.MaskFormatter data= new
            javax.swing.text.MaskFormatter("###.###.###-##");
            jFormattedTextFieldCpfSupervisor = new 
            javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        jLabel5 = new javax.swing.JLabel();
        jPasswordFieldSenhaSupervisor = new javax.swing.JPasswordField();
        jButtonFecharCaixa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Caso de Uso: Fechamento Caixa");
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setText("CPF Atendente:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 60, 110, 20);

        jFormattedTextFieldCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCpfFocusLost(evt);
            }
        });
        jPanel1.add(jFormattedTextFieldCpf);
        jFormattedTextFieldCpf.setBounds(50, 80, 110, 20);

        jLabel3.setText("Terminal:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 180, 110, 20);

        jPanel1.add(jComboBoxTerminal);
        jComboBoxTerminal.setBounds(50, 200, 110, 20);

        jLabel2.setText("Fundo do Fechamento:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 240, 130, 20);
        jPanel1.add(jTextFieldFundoFechamento);
        jTextFieldFundoFechamento.setBounds(50, 260, 110, 20);

        jLabel4.setText("CPF Supervisor:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 300, 110, 20);

        jFormattedTextFieldCpfSupervisor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCpfSupervisorFocusLost(evt);
            }
        });
        jPanel1.add(jFormattedTextFieldCpfSupervisor);
        jFormattedTextFieldCpfSupervisor.setBounds(50, 320, 110, 20);

        jLabel5.setText("Senha Supervisor:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 360, 110, 20);
        jPanel1.add(jPasswordFieldSenhaSupervisor);
        jPasswordFieldSenhaSupervisor.setBounds(50, 380, 110, 20);

        jButtonFecharCaixa.setText("Fechar Caixa");
        jButtonFecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharCaixaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFecharCaixa);
        jButtonFecharCaixa.setBounds(50, 420, 110, 23);

        jLabel6.setText("Senha Atendente:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 120, 110, 20);
        jPanel1.add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(50, 140, 110, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCpfFocusLost

        consultarCPF();
    }//GEN-LAST:event_jFormattedTextFieldCpfFocusLost

    private void jFormattedTextFieldCpfSupervisorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCpfSupervisorFocusLost

        consultarCPFSupervisor();
    }//GEN-LAST:event_jFormattedTextFieldCpfSupervisorFocusLost

    private void jButtonFecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharCaixaActionPerformed

        fecharCaixa();
    }//GEN-LAST:event_jButtonFecharCaixaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FechamentoCaixaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FechamentoCaixaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FechamentoCaixaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FechamentoCaixaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FechamentoCaixaFrame().setVisible(true);
                } catch (PDVException ex) {
                    MensagemUtil.addMensagemErro(ex.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFecharCaixa;
    private javax.swing.JComboBox jComboBoxTerminal;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfSupervisor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JPasswordField jPasswordFieldSenhaSupervisor;
    private javax.swing.JTextField jTextFieldFundoFechamento;
    // End of variables declaration//GEN-END:variables

    private void consultarCPF() {
        try {
            String cpf = jFormattedTextFieldCpf.getText();
            funcionario = servico.consultarPor(cpf);

            if (funcionario == null || funcionario.isTransient()) {
                throw new PDVException("CPF inválido.");
            } else {
                preencherComboBoxTerminal();
            }
        } catch (PDVException e) {
            MensagemUtil.addMensagemErro(e.getMessage());
            jFormattedTextFieldCpf.requestFocus();
        }
    }

    private void consultarCPFSupervisor() {
        try {
            String cpf = jFormattedTextFieldCpfSupervisor.getText();
            supervisor = servico.consultarPor(cpf);

            if (supervisor == null || supervisor.isTransient()
                    || supervisor.getCargo().getPerfil().equals(PerfilEnum.ATENDENTE.getNome())) {
                throw new PDVException("CPF do supervisor é inválido.");
            }
        } catch (PDVException e) {
            MensagemUtil.addMensagemErro(e.getMessage());
            jFormattedTextFieldCpfSupervisor.requestFocus();
        }
    }

    private void fecharCaixa() {
        try {
            validarCamposObrigatorios();
            String senha = StringUtil.criptografar(new String(jPasswordFieldSenha.getPassword()));
            String senhaSupervisor = StringUtil.criptografar(new String(jPasswordFieldSenhaSupervisor.getPassword()));

            if (!senha.equals(funcionario.getSenha())) {
                throw new PDVException("Senha inválida!");
            } else if (!senhaSupervisor.equals(supervisor.getSenha())) {
                throw new PDVException("Senha do supervisor é inválida!");
            } else {
                MovimentoCaixaServico caixaServico = new MovimentoCaixaServico();
                Double fundoCaixa = Double.parseDouble(jTextFieldFundoFechamento.getText());

                MovimentoCaixa caixa = new MovimentoCaixa();
                for (Terminal t : terminais) {
                    if (t.getNumero().equals(Integer.parseInt(jComboBoxTerminal.getSelectedItem().toString()))) {
                        caixa = caixaServico.consultarEmAbertoPor(t);
                        break;
                    }
                }

                caixa.setDataHoraFechamento(Calendar.getInstance().getTime());
                caixa.setFundoFechamento(fundoCaixa);

                caixaServico.atualizar(caixa);

                FrameUtil.funcionarioLogado = new Funcionario();
                new LoginFrame().setVisible(Boolean.TRUE);
                dispose();
            }
        } catch (PDVException e) {
            MensagemUtil.addMensagemErro(e.getMessage());
        }
    }

    private void preencherComboBoxTerminal() throws PDVException {
        jComboBoxTerminal.removeAllItems();
        jComboBoxTerminal.addItem(".:: SELECIONE ::.");

        String cpf = jFormattedTextFieldCpf.getText();
        terminais = new TerminalServico().consultarDisponiveisPor(cpf);

        for (Terminal t : terminais) {
            jComboBoxTerminal.addItem(t.getNumero().toString());
        }
    }

    private void validarCamposObrigatorios() throws PDVException {
        String cpf = jFormattedTextFieldCpf.getText();
        String cpfSupervisor = jFormattedTextFieldCpfSupervisor.getText();
        String fundo = jTextFieldFundoFechamento.getText();

        if (cpf == null || cpf.equals("") || cpf.equals("   .   .   -  ")
                || jPasswordFieldSenha.getPassword().length == 0
                || cpfSupervisor == null || cpfSupervisor.equals("") || cpfSupervisor.equals("   .   .   -  ")
                || jPasswordFieldSenhaSupervisor.getPassword().length == 0
                || jComboBoxTerminal.getSelectedIndex() == 0
                || fundo == null || fundo.equals("")) {
            jFormattedTextFieldCpf.setBorder(FrameUtil.BORDA_VERMELHA);
            jPasswordFieldSenha.setBorder(FrameUtil.BORDA_VERMELHA);
            jFormattedTextFieldCpfSupervisor.setBorder(FrameUtil.BORDA_VERMELHA);
            jPasswordFieldSenhaSupervisor.setBorder(FrameUtil.BORDA_VERMELHA);
            jComboBoxTerminal.setBorder(FrameUtil.BORDA_VERMELHA);
            jTextFieldFundoFechamento.setBorder(FrameUtil.BORDA_VERMELHA);

            throw new PDVException("Todos os campos devem ser preenchidos!");
        }
    }
}
