package br.com.devschool.login.visao;

import br.com.devschool.entidade.Funcionario;
import br.com.devschool.entidade.Terminal;
import br.com.devschool.funcionario.servico.FuncionarioServico;
import br.com.devschool.principal.visao.PrincipalFrame;
import br.com.devschool.terminal.servico.TerminalServico;
import br.com.devschool.util.FrameUtil;
import br.com.devschool.util.MensagemUtil;
import br.com.devschool.util.PDVException;
import br.com.devschool.util.StringUtil;
import br.com.devschool.util.enumerador.PerfilEnum;
import java.util.ArrayList;
import java.util.List;

/**
 * @author ATILLA
 */
public class LoginEmergencialFrame extends javax.swing.JFrame {

    private FuncionarioServico servico;
    private Funcionario funcionario = null;
    private Funcionario supervisor = null;
    private List<Terminal> terminais = new ArrayList();
    
    public LoginEmergencialFrame() {
        try {
            servico = new FuncionarioServico();
        } catch (PDVException ex) {
            MensagemUtil.addMensagemErro(ex.getMessage());
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField();
        try{
            javax.swing.text.MaskFormatter data= new
            javax.swing.text.MaskFormatter("###.###.###-##");
            jFormattedTextFieldCpf = new 
            javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        jLabel2 = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonLogar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jComboBoxTerminal = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldCpfSupervisor = new javax.swing.JFormattedTextField();
        try{
            javax.swing.text.MaskFormatter data= new
            javax.swing.text.MaskFormatter("###.###.###-##");
            jFormattedTextFieldCpfSupervisor = new 
            javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        jLabel5 = new javax.swing.JLabel();
        jPasswordFieldSenhaSupervisor = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Emergencial");
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setText("CPF Atendente:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(350, 90, 110, 20);

        jFormattedTextFieldCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCpfFocusLost(evt);
            }
        });
        jPanel1.add(jFormattedTextFieldCpf);
        jFormattedTextFieldCpf.setBounds(350, 110, 110, 20);

        jLabel2.setText("Senha Atendente:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(350, 150, 110, 20);
        jPanel1.add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(350, 170, 110, 20);

        jButtonLogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edit.png"))); // NOI18N
        jButtonLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogar);
        jButtonLogar.setBounds(350, 380, 50, 40);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/close.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSair);
        jButtonSair.setBounds(410, 380, 50, 40);

        jPanel1.add(jComboBoxTerminal);
        jComboBoxTerminal.setBounds(350, 230, 110, 20);

        jLabel3.setText("Terminal:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(350, 210, 110, 20);

        jLabel4.setText("CPF Supervisor:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 270, 110, 20);

        jFormattedTextFieldCpfSupervisor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCpfSupervisorFocusLost(evt);
            }
        });
        jPanel1.add(jFormattedTextFieldCpfSupervisor);
        jFormattedTextFieldCpfSupervisor.setBounds(350, 290, 110, 20);

        jLabel5.setText("Senha Supervisor:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 330, 110, 20);
        jPanel1.add(jPasswordFieldSenhaSupervisor);
        jPasswordFieldSenhaSupervisor.setBounds(350, 350, 110, 20);

        jButtonLogin.setText("Login Normal");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin);
        jButtonLogin.setBounds(350, 430, 110, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCpfFocusLost

        consultarCPF();
    }//GEN-LAST:event_jFormattedTextFieldCpfFocusLost

    private void jButtonLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogarActionPerformed

        logar();
    }//GEN-LAST:event_jButtonLogarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jFormattedTextFieldCpfSupervisorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCpfSupervisorFocusLost

        consultarCPFSupervisor();
    }//GEN-LAST:event_jFormattedTextFieldCpfSupervisorFocusLost

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed

        new LoginFrame().setVisible(Boolean.TRUE);
        dispose();
    }//GEN-LAST:event_jButtonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginEmergencialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginEmergencialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginEmergencialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginEmergencialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginEmergencialFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogar;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox jComboBoxTerminal;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfSupervisor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JPasswordField jPasswordFieldSenhaSupervisor;
    // End of variables declaration//GEN-END:variables

    private void consultarCPF() {
        try {
            String cpf = jFormattedTextFieldCpf.getText();
            funcionario = servico.consultarPor(cpf);
            
            if (funcionario == null || funcionario.isTransient()) {
                throw new PDVException("CPF inválido.");
            } else {
                preencherComboBoxTerminal();
            }
        } catch (PDVException e) {
            MensagemUtil.addMensagemErro(e.getMessage());
            jFormattedTextFieldCpf.requestFocus();
        }
    }
    
    private void consultarCPFSupervisor() {
        try {
            String cpf = jFormattedTextFieldCpfSupervisor.getText();
            supervisor = servico.consultarPor(cpf);
            
            if (supervisor == null || supervisor.isTransient() || 
                    supervisor.getCargo().getPerfil().equals(PerfilEnum.ATENDENTE.getNome())) {
                throw new PDVException("CPF do supervisor é inválido.");
            }
        } catch (PDVException e) {
            MensagemUtil.addMensagemErro(e.getMessage());
            jFormattedTextFieldCpfSupervisor.requestFocus();
        }
    }

    private void logar() {
        try {
            validarCamposObrigatorios();
            String senha = StringUtil.criptografar(new String(jPasswordFieldSenha.getPassword()));
            String senhaSupervisor = StringUtil.criptografar(new String(jPasswordFieldSenhaSupervisor.getPassword()));
                        
            if (!senha.equals(funcionario.getSenha())) {
                throw new PDVException("Senha inválida!");
            } else if (!senhaSupervisor.equals(supervisor.getSenha())) {
                throw new PDVException("Senha do supervisor é inválida!");
            } else {
                for (Terminal terminal : terminais) {
                    if (terminal.getNumero().toString().equals(jComboBoxTerminal.getSelectedItem())) {
                        FrameUtil.terminalLogado = terminal;
                        break;
                    }
                }
                
                FrameUtil.funcionarioLogado = funcionario;
                
                new PrincipalFrame().setVisible(Boolean.TRUE);
                dispose();
            }
        } catch (PDVException e) {
            MensagemUtil.addMensagemErro(e.getMessage());
        }
    }

    private void preencherComboBoxTerminal() {
        jComboBoxTerminal.removeAllItems();
        jComboBoxTerminal.addItem(".:: SELECIONE ::.");
    
        try {
            String cpf = jFormattedTextFieldCpf.getText();
            terminais = new TerminalServico().consultarDisponiveisPor(cpf);
            
            for (Terminal t : terminais) {
                jComboBoxTerminal.addItem(t.getNumero().toString());
            }
        } catch (PDVException ex) {
            MensagemUtil.addMensagemErro(ex.getMessage());
        }
    }

    private void validarCamposObrigatorios() throws PDVException {
        String cpf = jFormattedTextFieldCpf.getText();
        String cpfSupervisor = jFormattedTextFieldCpfSupervisor.getText();
            
        if (cpf == null || cpf.equals("") || cpf.equals("   .   .   -  ")
                || jPasswordFieldSenha.getPassword().length == 0
                || cpfSupervisor == null || cpfSupervisor.equals("") || cpfSupervisor.equals("   .   .   -  ")
                || jPasswordFieldSenhaSupervisor.getPassword().length == 0
                || jComboBoxTerminal.getSelectedIndex() == 0) {
            jFormattedTextFieldCpf.setBorder(FrameUtil.BORDA_VERMELHA);
            jPasswordFieldSenha.setBorder(FrameUtil.BORDA_VERMELHA);
            jFormattedTextFieldCpfSupervisor.setBorder(FrameUtil.BORDA_VERMELHA);
            jPasswordFieldSenhaSupervisor.setBorder(FrameUtil.BORDA_VERMELHA);
            jComboBoxTerminal.setBorder(FrameUtil.BORDA_VERMELHA);
            
            throw new PDVException("Todos os campos devem ser preenchidos!");
        }
    }
}
